### ISSUE TITLE
没有controller?

### ISSUE THREAD

**Issue by darkr4y** [fy0/fpage#1]
发现目录结构没有很清晰的标出controller
直接就在view中写了这样不太好

**Comment by fy0** [comment]
view其实就是controller，也就是负责处理请求的一层。

这个项目依然是MVC的底子，但MVC毕竟年代久远，有些概念说法很多，于是就使用了Django的MVT的概念。

**Comment by darkr4y** [comment]
仔细看了一遍代码后,明白了,没怎么用过Django,不好意思哈~
