### ISSUE TITLE
fix（close）

### ISSUE THREAD

**Issue by 521xueweihan** [fy0/fpage#2]
＝＝＝非常酷的项目＝＝＝

我的环境是：
python 2.7.11
torando 4.3
SQLAlchemy=1.0.11
Jinja2=2.8
启动报错：str() takes at most 1 argument (2 given)
问题原因：我认为是py2 和 3 的str方法接收参数问题
解决办法：
修改fpage/src/model :104行
改为：return session.query(cls).filter(cls.key==str(key or b'').encode('utf-8')).first()

其他问题：我clone下来fix这个问题时候，提交到您的远程库，403拒绝访问。所以就来这里了。前辈如果得空，可以给我github扫盲一下。

**Comment by fy0** [comment]
因为Github上直接提交是不允许的，不然的话任何人可以向任何版本库写代码了，不管是善意还是恶意的。

比较常规的姿势是提交 pull request

我会尽快搞掉这个问题

**Comment by fy0** [comment]
搞定。给出的资料很详实，感谢。 @521xueweihan

Python 2.7.10
Python 3.4.3
测试通过
